[project]
name = "langgraph-trial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.6.4",
    "langsmith>=0.4.13",
]
